from environment.environment import SELF, DATASET

# class
# SELF = 'D:\\Chi\\webimg-to-code\\'
CLASS_SEQ2SEQ_MODEL_GRAPH_FILE = SELF+'assets\\seq2seq-position\\seq2seq-model.png'

CLASS_SEQ2SEQ_TRAINING_TYPE = '2020-4\\seq2seq-data3\\attr-rowcolAttrElement\\encoder_bidirectional-stack-resort\\300\\noise\\'
CLASS_SEQ2SEQ_WEIGHT = SELF+'assets\\'+CLASS_SEQ2SEQ_TRAINING_TYPE+'weight\\'
CLASS_SEQ2SEQ_MODEL_PATH = SELF+'assets\\'+CLASS_SEQ2SEQ_TRAINING_TYPE+'model\\'
CLASS_SEQ2SEQ_ANALYSIS_PATH = SELF+'assets\\'+CLASS_SEQ2SEQ_TRAINING_TYPE
CLASS_SEQ2SEQ_PREDIT_GUI_PATH = SELF+'assets\\'+CLASS_SEQ2SEQ_TRAINING_TYPE+'test-predit-gui\\'

CLASS_ATTR_TRAINING_TYPE = '2020\\attr_class-pix2code-fix\\alexnet\\74224-256\\2500-p0\\'
CLASS_ATTR_WEIGHT = SELF + 'assets\\'+CLASS_ATTR_TRAINING_TYPE+'weight\\'
CLASS_ATTR_ANALYSIS =  SELF+'assets\\'+CLASS_ATTR_TRAINING_TYPE
CLASS_ATTR_PREDIT_GUI_PATH = SELF+'assets\\'+CLASS_ATTR_TRAINING_TYPE+'test-predit-gui\\'
CLASS_ATTR_MODEL_PATH = SELF+'assets\\'+CLASS_ATTR_TRAINING_TYPE+'model\\'

# PATH_PIX2CODE_DATASET = SELF+'dataset\\pix2code\\'
# PIX2CODE_POSITION_FOLDER = 'row-col-yolo-position-txt\\'
# PIX2CODE_GUI_FOLDER = 'row-col-gui\\'


# DATASET
# DATASET = 'D:\\Chi\\dataset\\'
DATASET1_ASSEST = SELF+'transform_pix2code_dataset\\assest\\'
DATASET1_ROWCOL_GUI = DATASET+'pix2code\\row-col-gui\\'
DATASET1_ROWCOL_ELEMENT_GUI = DATASET+'pix2code\\row-col-element-gui\\'
DATASET1_ROWCOL_ATTRIBUTE_GUI = DATASET+'pix2code\\row-col-attribute-gui\\'
DATASET1_ROWCOL_PNG = DATASET+'pix2code\\row-col-png\\'
DATASET1_ROWCOL_POSITION_TXT = DATASET+'pix2code\\row-col-position-txt\\'
DATASET1_ROWCOL_YOLO_POSITION_TXT = DATASET+'pix2code\\row-col-yolo-position-txt\\'
DATASET1_YOLO_POSITION_TXT = DATASET+'pix2code\\yolo-position-txt\\'
DATASET1_FULL_YOLO_POSITION_TXT = DATASET+'pix2code\\full-yolo-position-txt\\'
DATASET1_FULL_YOLO_POSITION_TXT_PADDING = DATASET+'pix2code\\full-yolo-position-txt-padding\\'
DATASET1_FULL_YOLO_POSITION_TXT_PADDING_20 = DATASET+'pix2code\\full-yolo-position-txt-padding20\\'
DATASET1_ATTRIBUTE_YOLO_POSITION_TXT = DATASET+'pix2code\\attribute-yolo-position-txt\\'
DATASET1_ATTRIBUTE_YOLO_POSITION_TXT_PADDING = DATASET+'pix2code\\attribute-yolo-position-txt-padding\\'
DATASET1_ATTRIBUTE_YOLO_POSITION_TXT_PADDING_20 = DATASET+'pix2code\\attribute-yolo-position-txt-padding20\\'
DATASET1_ORIGIN_PNG = DATASET+'pix2code\\origin-png\\'
DATASET1_ORIGIN_GUI = DATASET+'pix2code\\origin-gui\\'
DATASET1_ELEMENT_FOLDER = DATASET+'pix2code\\element\\'
DATASET1_ELEMENT_PNG = DATASET1_ELEMENT_FOLDER+'element-png\\'
DATASET1_ATTRCLASSFICATION_JSON = DATASET+'pix2code\\attribute-classification-json\\'
DATASET1_YOLO_TRAIN_DATA = DATASET+'pix2code\\yolo_train\\'
PIX2CODE_ORIGIN_DATASET = 'E:\\projects\\webGener\\pix2code\\datasets\\pix2code_datasets\\web\\all_data\\'




DATASET1_FULL_YOLO_NOISE = DATASET+'pix2code\\full-yolo-noise-resort-txt\\'
DATASET1_FULL_YOLO_NOISE_TXT = DATASET1_FULL_YOLO_NOISE+"position_txt\\"
DATASET1_FULL_YOLO_NOISE_TXT_PADDING = DATASET1_FULL_YOLO_NOISE+"position_txt_padding\\"
DATASET1_FULL_YOLO_NOISE_TXT_PADDING_20 = DATASET1_FULL_YOLO_NOISE+"position_txt_padding20\\"
DATASET1_ATTR_YOLO_NOISE_TXT = DATASET1_FULL_YOLO_NOISE+"attr-position_txt\\"
DATASET1_ATTR_YOLO_NOISE_TXT_PADDING = DATASET1_FULL_YOLO_NOISE+"attr-position_txt_padding\\"
DATASET1_ATTR_YOLO_NOISE_TXT_PADDING_20 = DATASET1_FULL_YOLO_NOISE+"attr-position_txt_padding20\\"
DATASET1_FULL_YOLO_NOISE_GUI = DATASET1_FULL_YOLO_NOISE+"gui\\"

DATASET1_TESTING = DATASET + 'pix2code\\testing-dataset\\'
DATASET1_TESTING_SEQ2SEQ_ATTR_GUI = DATASET1_TESTING+'seq2seq\\attr-gui\\'
DATASET1_TESTING_SEQ2SEQ_POSITION_TXT = DATASET1_TESTING+'seq2seq\\position-txt\\'
DATASET1_TESTING_SEQ2SEQ_POSITION_TXT_PADDING = DATASET1_TESTING+'seq2seq\\position-txt-padding\\'
DATASET1_TESTING_SEQ2SEQ_POSITION_TXT_PADDING_20 = DATASET1_TESTING+'seq2seq\\position-txt-padding20\\'
DATASET1_TESTING_SEQ2SEQ_ATTR_POSITION_TXT = DATASET1_TESTING+'seq2seq\\attr-position-txt\\'
DATASET1_TESTING_SEQ2SEQ_ATTR_POSITION_TXT_PADDING = DATASET1_TESTING+'seq2seq\\attr-position-txt-padding\\'
DATASET1_TESTING_SEQ2SEQ_ATTR_POSITION_TXT_PADDING_20 = DATASET1_TESTING+'seq2seq\\attr-position-txt-padding20\\'

DATASET1_TESTING_SEQ2SEQ_POSITION_NOISE_TXT = DATASET1_TESTING+'seq2seq\\noise\\position-txt\\'
DATASET1_TESTING_SEQ2SEQ_POSITION_NOISE_TXT_PADDING = DATASET1_TESTING+'seq2seq\\noise\\position-txt-padding\\'
DATASET1_TESTING_SEQ2SEQ_POSITION_NOISE_TXT_PADDING_20 = DATASET1_TESTING+'seq2seq\\noise\\position-txt-padding20\\'
DATASET1_TESTING_SEQ2SEQ_ATTR_POSITION_NOISE_TXT = DATASET1_TESTING+'seq2seq\\noise\\attr-position-txt\\'
DATASET1_TESTING_SEQ2SEQ_ATTR_POSITION_NOISE_TXT_PADDING = DATASET1_TESTING+'seq2seq\\noise\\attr-position-txt-padding\\'
DATASET1_TESTING_SEQ2SEQ_ATTR_POSITION_NOISE_TXT_PADDING_20 = DATASET1_TESTING+'seq2seq\\noise\\attr-position-txt-padding20\\'
DATASET1_TESTING_SEQ2SEQ_ATTR_NOISE_GUI = DATASET1_TESTING+'seq2seq\\noise\\attr-gui\\'




DATASET2_ASSESTS = SELF+'datasetCode\\dataset_2_generator\\assests\\'
DATASET2_ORIGIN_GUI = DATASET+'dataset2\\origin_gui\\'
DATASET2_ORIGIN_HTML = DATASET+'dataset2\\origin_html\\'
DATASET2_ORIGIN_PNG = DATASET+'dataset2\\origin_png\\'
DATASET2_ORIGIN_LARGE_PNG = DATASET+'dataset2\\origin_large_png\\'
DATASET2_ROWCOL_GUI = DATASET+'dataset2\\row_col_gui\\'
DATASET2_ORIGIN_NO_CONTEXT_GUI = DATASET+'dataset2\\origin_no_context_gui\\'
DATASET2_ROWCOL_IMG = DATASET+'dataset2\\row_col_png\\'
DATASET2_ROWCOL_LARGE_IMG = DATASET+'dataset2\\row_col_large_png\\'
DATASET2_ROWCOL_YOLO_POSITION_TXT = DATASET+'dataset2\\row_col_yolo_position_txt\\'
DATASET2_YOLO_POSITION_TXT = DATASET+'dataset2\\yolo_position_txt\\'
DATASET2_FULL_YOLO_POSITION_TXT = DATASET+'dataset2\\full_yolo_position_txt\\'

# DATASET2_ORIGIN_PNG_PATH = DATASET+'dataset2\\origin_png'

DATASET2_DSL_MAPPING_JSON_FILE = SELF+'datasetCode\\dataset_2_generator\\mapping\\web-dsl-mapping-pix2code.json'



DATASET3 = 'dataset3\\'
DATASET3_ORIGIN_GUI = DATASET+DATASET3+'origin_gui\\'
DATASET3_ORIGIN_HTML = DATASET+DATASET3+'origin_html\\'
DATASET3_ORIGIN_LIGHT_HTML = DATASET+DATASET3+'origin_light_html\\'
DATASET3_ORIGIN_PNG = DATASET+DATASET3+'origin_png\\'
DATASET3_ORIGIN_LIGHT_PNG = DATASET+DATASET3+'origin_light_png\\'
DATASET3_ORIGIN_NO_CONTEXT_GUI = DATASET+DATASET3+'origin_no_context_gui\\'
DATASET3_ROWCOL_IMG = DATASET+DATASET3+'row_col_png\\'
DATASET3_ROWCOL_YOLO_POSITION_TXT = DATASET+DATASET3+'row_col_yolo_position_txt\\'
DATASET3_FULL_YOLO_POSITION_TXT = DATASET+DATASET3+'full_yolo_position_txt\\'
DATASET3_FULL_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+'full_yolo_position_txt_padding\\'
DATASET3_FULL_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+'full_yolo_position_txt_input_padding\\'
DATASET3_FULL_YOLO_POSITION_TXT_PADDING_20 = DATASET+DATASET3+'full_yolo_position_txt_padding20\\'
DATASET3_ATTR_YOLO_POSITION_TXT = DATASET+DATASET3+'attr_yolo_position_txt\\'
DATASET3_ATTR_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+'attr_yolo_position_txt_padding\\'
DATASET3_ATTR_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+'attr_yolo_position_txt_input_padding\\'
DATASET3_ATTR_YOLO_POSITION_TXT_PADDING_20 = DATASET+DATASET3+'attr_yolo_position_txt_padding20\\'
DATASET3_ELEMENT_FOLDER = DATASET+DATASET3+'element\\'
DATASET3_ELEMENT_PNG = DATASET3_ELEMENT_FOLDER+'element_png\\'
DATASET3_ELEMENT_PNG_PADDING = DATASET3_ELEMENT_FOLDER+'element_png_padding\\'
DATASET3_ELEMENT_PNG_PADDING_20 = DATASET3_ELEMENT_FOLDER+'element_png_padding20\\'

TRAINSET = 'train_set\\'
TESTSET = 'test_set\\'
DATASET3_TRAINSET_ORIGIN_GUI = DATASET+DATASET3+TRAINSET+'origin_gui\\'
DATASET3_TRAINSET_ORIGIN_NO_CONTEXT_GUI = DATASET+DATASET3+TRAINSET+'origin_no_context_gui\\'
DATASET3_TRAINSET_ORIGIN_LIGHT_PNG = DATASET+DATASET3+TRAINSET+'origin_light_png\\'
DATASET3_TRAINSET_FULL_YOLO_POSITION_TXT = DATASET+DATASET3+TRAINSET+'full_yolo_position_txt\\'
DATASET3_TRAINSET_FULL_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+TRAINSET+'full_yolo_position_txt_padding\\'
DATASET3_TRAINSET_FULL_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+TRAINSET+'full_yolo_position_txt_input_padding\\'
DATASET3_TRAINSET_FULL_YOLO_POSITION_TXT_PADDING_2 = DATASET+DATASET3+TRAINSET+'full_yolo_position_txt_padding_2\\'
DATASET3_TRAINSET_ATTR_YOLO_POSITION_TXT = DATASET+DATASET3+TRAINSET+'attr_yolo_position_txt\\'
DATASET3_TRAINSET_ATTR_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+TRAINSET+'attr_yolo_position_txt_padding\\'
DATASET3_TRAINSET_ATTR_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+TRAINSET+'attr_yolo_position_txt_input_padding\\'
DATASET3_TRAINSET_ATTR_YOLO_POSITION_TXT_PADDING_2 = DATASET+DATASET3+TRAINSET+'attr_yolo_position_txt_padding20\\'

DATASET3_TRAINSET_NOISE_ORIGIN_GUI = DATASET+DATASET3+TRAINSET+'noise\\origin_gui\\'
DATASET3_TRAINSET_NOISE_ORIGIN_NO_CONTEXT_GUI = DATASET+DATASET3+TRAINSET+'noise\\origin_no_context_gui\\'
DATASET3_TRAINSET_NOISE_FULL_YOLO_POSITION_TXT = DATASET+DATASET3+TRAINSET+'noise\\full_yolo_position_txt\\'
DATASET3_TRAINSET_NOISE_FULL_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+TRAINSET+'noise\\full_yolo_position_txt_padding\\'
DATASET3_TRAINSET_NOISE_FULL_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+TRAINSET+'noise\\full_yolo_position_txt_input_padding\\'
DATASET3_TRAINSET_NOISE_FULL_YOLO_POSITION_TXT_PADDING_2 = DATASET+DATASET3+TRAINSET+'noise\\full_yolo_position_txt_padding20\\'
DATASET3_TRAINSET_NOISE_ATTR_YOLO_POSITION_TXT = DATASET+DATASET3+TRAINSET+'noise\\attr_yolo_position_txt\\'
DATASET3_TRAINSET_NOISE_ATTR_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+TRAINSET+'noise\\attr_yolo_position_txt_padding\\'
DATASET3_TRAINSET_NOISE_ATTR_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+TRAINSET+'noise\\attr_yolo_position_txt_input_padding\\'
DATASET3_TRAINSET_NOISE_ATTR_YOLO_POSITION_TXT_PADDING_2 = DATASET+DATASET3+TRAINSET+'noise\\attr_yolo_position_txt_padding20\\'
DATASET3_TRAINSET_YOLO_TRAIN_TXT = DATASET+DATASET3+TRAINSET+'yolo_train\\'

DATASET3_TESTSET_ORIGIN_GUI = DATASET+DATASET3+TESTSET+'origin_gui\\'
DATASET3_TESTSET_ORIGIN_NO_CONTEXT_GUI = DATASET+DATASET3+TESTSET+'origin_no_context_gui\\'
DATASET3_TESTSET_ORIGIN_LIGHT_PNG = DATASET+DATASET3+TESTSET+'origin_light_png\\'
DATASET3_TESTSET_FULL_YOLO_POSITION_TXT = DATASET+DATASET3+TESTSET+'full_yolo_position_txt\\'
DATASET3_TESTSET_FULL_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+TESTSET+'full_yolo_position_txt_padding\\'
DATASET3_TESTSET_FULL_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+TESTSET+'full_yolo_position_txt_input_padding\\'
DATASET3_TESTSET_FULL_YOLO_POSITION_TXT_PADDING_2 = DATASET+DATASET3+TESTSET+'full_yolo_position_txt_padding20\\'
DATASET3_TESTSET_ATTR_YOLO_POSITION_TXT = DATASET+DATASET3+TESTSET+'attr_yolo_position_txt\\'
DATASET3_TESTSET_ATTR_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+TESTSET+'attr_yolo_position_txt_padding\\'
DATASET3_TESTSET_ATTR_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+TESTSET+'attr_yolo_position_txt_input_padding\\'
DATASET3_TESTSET_ATTR_YOLO_POSITION_TXT_PADDING_2 = DATASET+DATASET3+TESTSET+'attr_yolo_position_txt_padding20\\'
DATASET3_TESTSET_NOISE_ORIGIN_GUI = DATASET+DATASET3+TESTSET+'noise\\origin_gui\\'
DATASET3_TESTSET_NOISE_ORIGIN_NO_CONTEXT_GUI = DATASET+DATASET3+TESTSET+'noise\\origin_no_context_gui\\'
DATASET3_TESTSET_NOISE_FULL_YOLO_POSITION_TXT = DATASET+DATASET3+TESTSET+'noise\\full_yolo_position_txt\\'
DATASET3_TESTSET_NOISE_FULL_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+TESTSET+'noise\\full_yolo_position_txt_padding\\'
DATASET3_TESTSET_NOISE_FULL_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+TESTSET+'noise\\full_yolo_position_txt_input_padding\\'
DATASET3_TESTSET_NOISE_FULL_YOLO_POSITION_TXT_PADDING_2 = DATASET+DATASET3+TESTSET+'noise\\full_yolo_position_txt_padding20\\'
DATASET3_TESTSET_NOISE_ATTR_YOLO_POSITION_TXT = DATASET+DATASET3+TESTSET+'noise\\attr_yolo_position_txt\\'
DATASET3_TESTSET_NOISE_ATTR_YOLO_POSITION_TXT_PADDING = DATASET+DATASET3+TESTSET+'noise\\attr_yolo_position_txt_padding\\'
DATASET3_TESTSET_NOISE_ATTR_YOLO_POSITION_TXT_INPUT_PADDING = DATASET+DATASET3+TESTSET+'noise\\attr_yolo_position_txt_input_padding\\'
DATASET3_TESTSET_NOISE_ATTR_YOLO_POSITION_TXT_PADDING_2 = DATASET+DATASET3+TESTSET+'noise\\attr_yolo_position_txt_padding20\\'



DATASET3_DSL_MAPPING_JSON_FILE = SELF+'datasetCode\\dataset_2_generator\\mapping\\web-dsl-mapping-dataset3.json'












DATASETCODE_ASSESTS = SELF+'datasetCode\\assests\\'



EVALUATION_BLEU_SCORE = SELF+'evaluation\\bleu_score\\'
EVALUATION_SEQ2SEQ_EVALUATION = SELF+'evaluation\\seq2seq_evaluation\\'

YOLO_DETECTED_FULL_POSITION_TXT = SELF + 'yolo_detected\\arch1_full_yolo_position\\'
YOLO_DETECTED_FULL_POSITION_TEST_TXT = SELF + 'yolo_detected\\arch1_full_yolo_position_test\\'
YOLO_DETECTED_ATTRIBUTE_POSITION_TXT = SELF + 'yolo_detected\\arch2_full_yolo_position\\'
YOLO_DETECTED_ATTRIBUTE_POSITION_TEST_TXT = SELF + 'yolo_detected\\arch2_full_yolo_position_test\\'

YOLO_DETECTED_DATA3_FULL_POSITION_TXT = SELF + 'yolo_detected\\data3\\arch1_train\\003-1\\'
